language: go
go:
    - tip

before_install:
    go get github.com/rakyll/statik

services:
    - docker

after_success:
- test -n "$TRAVIS_TAG" && docker login -u=hendry -p="$DOCKER_PASSWORD"

deploy:
    - provider: script
      skip_cleanup: true
      script: curl -sL https://git.io/goreleaser | bash
      on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux
